"""Fuzzy recovery of payment references from bank narrations.

The helpers in this module are deliberately pure and operate only on their
arguments.  Confusable expansion is capped at 1,024 variants and at two
substitutions so hostile or unusually long tokens cannot cause combinatorial
growth.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import combinations
import re
from typing import Literal


MAX_CONFUSABLE_VARIANTS = 1_024
MAX_CONFUSABLE_SUBSTITUTIONS = 2

_PREFIX_LENGTH = 6
_CONFUSABLES = {
    "0": "O",
    "O": "0",
    "1": "I",
    "I": "1",
    "5": "S",
    "S": "5",
    "8": "B",
    "B": "8",
    "2": "Z",
    "Z": "2",
    "6": "G",
    "G": "6",
}

FuzzyStrategy = Literal["exact", "confusable", "prefix", "edit_distance"]


@dataclass(frozen=True)
class FuzzyResult:
    """All references surviving the first successful recovery strategy.

    ``scores`` contains a distance for each candidate: zero for exact hits,
    substitutions for confusable hits, omitted suffix length for prefix hits,
    and Levenshtein distance for edit-distance hits.
    """

    candidates: list[str]
    strategy: FuzzyStrategy | None
    scores: dict[str, int]

    @property
    def references(self) -> list[str]:
        """Alias for callers that describe candidates as references."""

        return self.candidates

    @property
    def distances(self) -> dict[str, int]:
        """Alias for the per-candidate scores, which are distance-like."""

        return self.scores


def extract_candidate_tokens(narration: str) -> list[str]:
    """Return distinct uppercase ASCII-alphanumeric runs of length six or more."""

    tokens: list[str] = []
    seen: set[str] = set()
    for token in re.findall(r"[A-Z0-9]{6,}", narration.upper()):
        if token not in seen:
            seen.add(token)
            tokens.append(token)
    return tokens


def expand_confusables(token: str, max_substitutions: int = 2) -> set[str]:
    """Return confusable variants of *token* within the bounded substitution count.

    Variants are generated by increasing substitution count and then by source
    position.  If more than :data:`MAX_CONFUSABLE_VARIANTS` are reachable, that
    deterministic generation order is truncated at the cap.  The original token
    is always included.
    """

    substitution_limit = min(
        max(0, max_substitutions), MAX_CONFUSABLE_SUBSTITUTIONS
    )
    positions = [index for index, character in enumerate(token) if character in _CONFUSABLES]
    variants = {token}

    for substitution_count in range(1, substitution_limit + 1):
        for selected_positions in combinations(positions, substitution_count):
            characters = list(token)
            for position in selected_positions:
                characters[position] = _CONFUSABLES[characters[position]]
            variants.add("".join(characters))
            if len(variants) >= MAX_CONFUSABLE_VARIANTS:
                return variants

    return variants


def prefix_candidates(
    token: str,
    prefix_index: dict[str, list[str]],
    min_prefix: int = 6,
) -> list[str]:
    """Return indexed references for which *token* is a sufficiently long prefix."""

    normalized_token = token.upper()
    if len(normalized_token) < max(_PREFIX_LENGTH, min_prefix):
        return []

    bucket = prefix_index.get(normalized_token[:_PREFIX_LENGTH], [])
    return sorted(
        {
            reference
            for reference in bucket
            if reference.startswith(normalized_token)
        }
    )


def edit_distance_at_most(
    a: str,
    b: str,
    max_distance: int = 2,
) -> int | None:
    """Return Levenshtein distance when it is at most *max_distance*.

    Only cells inside the distance band are evaluated.  Cells already beyond
    the bound are discarded, allowing a row with no viable path to exit early.
    """

    if max_distance < 0:
        raise ValueError("max_distance must be non-negative")
    if a == b:
        return 0
    if abs(len(a) - len(b)) > max_distance:
        return None

    previous = {
        column: column for column in range(0, min(len(b), max_distance) + 1)
    }

    for row in range(1, len(a) + 1):
        first_column = max(0, row - max_distance)
        last_column = min(len(b), row + max_distance)
        current: dict[int, int] = {}

        if first_column == 0 and row <= max_distance:
            current[0] = row

        for column in range(max(1, first_column), last_column + 1):
            deletion = previous.get(column, max_distance + 1) + 1
            insertion = current.get(column - 1, max_distance + 1) + 1
            substitution = previous.get(column - 1, max_distance + 1) + (
                a[row - 1] != b[column - 1]
            )
            distance = min(deletion, insertion, substitution)
            if distance <= max_distance:
                current[column] = distance

        if not current:
            return None
        previous = current

    return previous.get(len(b))


def recover_reference(
    narration: str,
    known_references: set[str],
    prefix_index: dict[str, list[str]],
) -> FuzzyResult:
    """Recover all references surviving the first successful fuzzy stage."""

    tokens = extract_candidate_tokens(narration)

    exact_scores = {token: 0 for token in tokens if token in known_references}
    if exact_scores:
        return _make_result("exact", exact_scores)

    confusable_scores: dict[str, int] = {}
    for token in tokens:
        for candidate in expand_confusables(token):
            if candidate not in known_references:
                continue
            distance = sum(left != right for left, right in zip(token, candidate))
            confusable_scores[candidate] = min(
                distance, confusable_scores.get(candidate, distance)
            )
    if confusable_scores:
        return _make_result("confusable", confusable_scores)

    prefix_scores: dict[str, int] = {}
    for token in tokens:
        for candidate in prefix_candidates(token, prefix_index):
            if candidate not in known_references:
                continue
            distance = len(candidate) - len(token)
            prefix_scores[candidate] = min(
                distance, prefix_scores.get(candidate, distance)
            )
    if prefix_scores:
        return _make_result("prefix", prefix_scores)

    edit_scores: dict[str, int] = {}
    for token in tokens:
        if len(token) < _PREFIX_LENGTH:
            continue
        bucket = prefix_index.get(token[:_PREFIX_LENGTH], [])
        for candidate in sorted(set(bucket)):
            if candidate not in known_references:
                continue
            distance = edit_distance_at_most(token, candidate, max_distance=2)
            if distance is None:
                continue
            edit_scores[candidate] = min(
                distance, edit_scores.get(candidate, distance)
            )
    if edit_scores:
        return _make_result("edit_distance", edit_scores)

    return FuzzyResult(candidates=[], strategy=None, scores={})


def _make_result(strategy: FuzzyStrategy, scores: dict[str, int]) -> FuzzyResult:
    candidates = sorted(scores)
    ordered_scores = {candidate: scores[candidate] for candidate in candidates}
    return FuzzyResult(candidates=candidates, strategy=strategy, scores=ordered_scores)
