"""Regenerate the README's dataset table from the data actually on disk.

Hand-maintained metrics tables go stale the moment a config knob moves -- this
one went stale twice during the generator's own development, both times quoting
numbers from a superseded amount distribution.  A README whose headline figures
disagree with `make verify` is worse than one with no figures, so the table is
generated rather than typed.

Run via `make stats` (and it runs as part of `make verify`).
"""

from __future__ import annotations

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from ambiguity import measure  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[1]
START = "<!-- STATS:START -->"
END = "<!-- STATS:END -->"


def build_table() -> str:
    rows = {}
    for name, seed_label in (("dev", "seed 42"), ("holdout", "seed 20260905")):
        d = ROOT / "data" / name
        meta = json.loads((d / "dataset_meta.json").read_text())
        amb = measure(d)
        rows[name] = {
            "label": f"{name} ({seed_label})",
            "gateway": meta["n_gateway_rows"],
            "bank": meta["n_bank_rows"],
            "links": meta["n_links"],
            "pairs": meta["n_truth_pairs"],
            "ceiling": f"{amb['deterministic_ceiling']:.1%}",
            "ambiguous": amb["ambiguous"],
            "examined": amb["examined"],
        }

    dev, hol = rows["dev"], rows["holdout"]
    return "\n".join([
        START,
        f"| | {dev['label']} | {hol['label']} |",
        "|---|---|---|",
        f"| Gateway rows | {dev['gateway']} | {hol['gateway']} |",
        f"| Bank credits | {dev['bank']} | {hol['bank']} |",
        f"| Truth links | {dev['links']} | {hol['links']} |",
        f"| Truth pairs | {dev['pairs']} | {hol['pairs']} |",
        f"| Ambiguous on amount+date | {dev['ambiguous']} / {dev['examined']} | "
        f"{hol['ambiguous']} / {hol['examined']} |",
        f"| **Deterministic ceiling** | **{dev['ceiling']}** | **{hol['ceiling']}** |",
        "",
        f"<sub>Table generated by `make stats` from the data in `data/`. "
        f"Do not edit by hand.</sub>",
        END,
    ])


def main() -> int:
    readme = ROOT / "README.md"
    text = readme.read_text()
    if START not in text or END not in text:
        print(f"error: {START} / {END} markers missing from README.md", file=sys.stderr)
        return 1
    head, _, rest = text.partition(START)
    _, _, tail = rest.partition(END)
    readme.write_text(head + build_table() + tail)
    print("README stats table refreshed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
